### ISSUE TITLE
STM32F796NI Mbed debuging error

### ISSUE THREAD

**Issue by JoanOG** [ARMmbed/Handbook#1491]
When I try to debug with the mbed studio I get the following error:

0001859:INFO:rom_table:    [2]
0001860:INFO:rom_table:    [3]
0001861:INFO:rom_table:  [1]
0001863:INFO:rom_table:[1]
0001864:INFO:dwt:4 hardware watchpoints
0001868:INFO:fpb:8 hardware breakpoints, 1 literal comparators
0001876:CRITICAL:__main__:No cores were discovered!
Traceback (most recent call last):
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\__main__.py", line 402, in run
    self._COMMANDS[self._args.cmd](self)
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\__main__.py", line 746, in do_gdbserver
    with session:
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\core\session.py", line 339, in __enter__
    self.open()
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\core\session.py", line 457, in open
    self._board.init()
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\board\board.py", line 85, in init
    self.target.init()
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\core\soc_target.py", line 117, in init
    seq.invoke()
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\utility\sequencer.py", line 208, in invoke
    resultSequence = call()
  File "c:\Users\JGonza12\AppData\Local\Mbed Studio\mbed-studio-tools\python\lib\site-packages\pyocd\coresight\coresight_target.py", line 214, in check_for_cores
    raise exceptions.DebugError("No cores were discovered!")
pyocd.core.exceptions.DebugError: No cores were discovered!
"GDB server stopped unexpectedly with exit code 1"

Any idea?

**Comment by 0xc0170** [comment]
please ask on the forum rather than docs (not related to the documentation).

Does pyocd work if you execute it directly? what version of pyocd or mbed studio is installed
